
const CARS = [
    {
        "id": "bmw-x3-2026",
        "brand": "BMW",
        "model": "X3",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 258,
        "transmission": "Автомат",
        "drivetrain": "Полный привод",
        "mileage": 4000,
        "price": 7530000,
        "features": [
            "M Sport пакет · Панорамная крыша",
            "Кожаный салон · Электропривод сидений",
            "Камера 360° · Парктроники",
            "Адаптивный круиз-контроль",
            "Светодиодные фары · Бесключевой доступ",
            "Подогрев и вентиляция сидений",
            "Harman Kardon аудиосистема",
            "Цена под ключ"
        ],
        "location": "Корея",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/bmw-x3/bmw-x3-1.jpg",
            "images/cars/bmw-x3/bmw-x3-2.jpg",
            "images/cars/bmw-x3/bmw-x3-3.jpg",
            "images/cars/bmw-x3/bmw-x3-4.jpg",
            "images/cars/bmw-x3/bmw-x3-5.jpg",
            "images/cars/bmw-x3/bmw-x3-6.jpg",
            "images/cars/bmw-x3/bmw-x3-7.jpg",
            "images/cars/bmw-x3/bmw-x3-8.jpg"
        ]
    },
    {
        "id": "mazda-cx5-2026",
        "brand": "Mazda",
        "model": "CX-5",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 155,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2530000,
        "priceIsFrom": true,
        "features": [
            "4 комплектации на выбор",
            "Zihiang — 2 530 000 ₽: LED фары, камера заднего вида, климат-контроль",
            "Zihiang Pro — 2 750 000 ₽: доп. 18\" диски, бесключевой доступ",
            "Zia — 2 990 000 ₽: кожаный салон, панорамная крыша, камера 360°",
            "Zia Pro — 3 100 000 ₽: максимальная · электропривод сидений, HUD, BOSE"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/mazda-cx5/mazda-cx5-1.jpg",
            "images/cars/mazda-cx5/mazda-cx5-2.jpg",
            "images/cars/mazda-cx5/mazda-cx5-3.jpg",
            "images/cars/mazda-cx5/mazda-cx5-4.jpg",
            "images/cars/mazda-cx5/mazda-cx5-5.jpg",
            "images/cars/mazda-cx5/mazda-cx5-6.jpg",
            "images/cars/mazda-cx5/mazda-cx5-7.jpg",
            "images/cars/mazda-cx5/mazda-cx5-8.jpg",
            "images/cars/mazda-cx5/mazda-cx5-9.jpg",
            "images/cars/mazda-cx5/mazda-cx5-10.jpg"
        ]
    },
    {
        "id": "nissan-qashqai-2026",
        "brand": "Nissan",
        "model": "Qashqai",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 140,
        "transmission": "Вариатор",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2290000,
        "priceIsFrom": true,
        "features": [
            "2 комплектации на выбор",
            "Edition — 2 290 000 ₽: LED фары, 17\" диски, климат-контроль, камера зад. вида",
            "Leading Edition — 2 350 000 ₽: 18\" диски, панорамный люк, камера 360°, кожаный руль, электропривод сидений, адаптивный круиз-контроль"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/nissan-qashqai/nissan-qashqai-1.jpg",
            "images/cars/nissan-qashqai/nissan-qashqai-2.jpg",
            "images/cars/nissan-qashqai/nissan-qashqai-3.jpg",
            "images/cars/nissan-qashqai/nissan-qashqai-4.jpg",
            "images/cars/nissan-qashqai/nissan-qashqai-5.jpg"
        ]
    },
    {
        "id": "bmw-320l-2023",
        "brand": "BMW",
        "model": "320L",
        "year": 2023,
        "engineVolume": 2,
        "horsePower": 156,
        "transmission": "Автомат",
        "drivetrain": "Задний привод",
        "mileage": 30000,
        "price": 3090000,
        "priceIsFrom": true,
        "features": [
            "M Sport пакет · Длиннобазная версия (+14 см)",
            "Кожаный салон · Электропривод сидений",
            "Панорамная крыша · Климат-контроль",
            "Камера заднего вида · Парктроники",
            "Адаптивный круиз-контроль",
            "Заводской окрас · Бесключевой доступ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/BMW-320L/BMW-320L-1.jpg",
            "images/cars/BMW-320L/BMW-320L-2.jpg",
            "images/cars/BMW-320L/BMW-320L-3.jpg",
            "images/cars/BMW-320L/BMW-320L-4.jpg",
            "images/cars/BMW-320L/BMW-320L-5.jpg",
            "images/cars/BMW-320L/BMW-320L-6.jpg",
            "images/cars/BMW-320L/BMW-320L-7.jpg"
        ]
    },
    {
        "id": "audi-q3-2021",
        "brand": "Audi",
        "model": "Q3",
        "year": 2021,
        "engineVolume": 1.4,
        "horsePower": 150,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 49000,
        "price": 2950000,
        "features": [
            "Панорамная крыша · Кожаный салон",
            "Климат-контроль · Подогрев сидений",
            "Электрорегулировка передних сидений",
            "Активная система экстренного торможения",
            "Камера заднего вида · Парктроники перед/зад",
            "Адаптивный круиз-контроль",
            "Электропривод багажника",
            "Автозатемнение салонного зеркала",
            "Бесключевой доступ · LED фары",
            "Заводской окрас · Пробег 49 000 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/audi-q3/audi-q3-1.jpg",
            "images/cars/audi-q3/audi-q3-2.jpg",
            "images/cars/audi-q3/audi-q3-3.jpg",
            "images/cars/audi-q3/audi-q3-4.jpg",
            "images/cars/audi-q3/audi-q3-5.jpg",
            "images/cars/audi-q3/audi-q3-6.jpg",
            "images/cars/audi-q3/audi-q3-7.jpg",
            "images/cars/audi-q3/audi-q3-8.jpg"
        ]
    },
    {
        "id": "nissan-xtrail-2026",
        "brand": "Nissan",
        "model": "X-Trail",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 141,
        "transmission": "Вариатор",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2450000,
        "priceIsFrom": true,
        "features": [
            "2 комплектации на выбор",
            "Edition — 2 450 000 ₽: камера 360°, ЖК-экран 12,3\", климат-контроль, бесключевой доступ, электропривод сидений",
            "Leading Edition — 2 530 000 ₽: панорамная крыша, LED фары, кожаный руль, 6 динамиков, адаптивный круиз-контроль"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/nissan-xtrail-2026/nissan-xtrail-2026-1.jpg",
            "images/cars/nissan-xtrail-2026/nissan-xtrail-2026-2.jpg",
            "images/cars/nissan-xtrail-2026/nissan-xtrail-2026-3.jpg",
            "images/cars/nissan-xtrail-2026/nissan-xtrail-2026-4.jpg",
            "images/cars/nissan-xtrail-2026/nissan-xtrail-2026-5.jpg",
            "images/cars/nissan-xtrail-2026/nissan-xtrail-2026-6.jpg"
        ]
    },
    {
        "id": "kia-seltos-2026",
        "brand": "Kia",
        "model": "Seltos",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 115,
        "transmission": "Автомат (CVT)",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2155000,
        "priceIsFrom": true,
        "features": [
            "Климат-контроль · LED фары",
            "Камера заднего вида · Парктроники",
            "Круиз-контроль · ЖК-экран",
            "Бесключевой доступ · Подогрев сидений",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/kia-seltos-2026/kia-seltos-2026-1.jpg",
            "images/cars/kia-seltos-2026/kia-seltos-2026-2.jpg",
            "images/cars/kia-seltos-2026/kia-seltos-2026-3.jpg",
            "images/cars/kia-seltos-2026/kia-seltos-2026-4.jpg",
            "images/cars/kia-seltos-2026/kia-seltos-2026-5.jpg",
            "images/cars/kia-seltos-2026/kia-seltos-2026-6.jpg"
        ],
        "tags": [
            "Компактный кроссовер",
            "Экономичный"
        ]
    },
    {
        "id": "hyundai-elantra-2025",
        "brand": "Hyundai",
        "model": "Elantra",
        "year": 2025,
        "engineVolume": 1.5,
        "horsePower": 115,
        "transmission": "Вариатор (CVT)",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2230000,
        "features": [
            "Панорамный люк · Кожаный салон",
            "Климат-контроль · Подогрев сидений и руля",
            "LED фары · 17\" легкосплавные диски",
            "ЖК-приборная панель · Круиз-контроль",
            "Бесключевой доступ · Камера заднего вида",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/hyundai-elantra-2025/hyundai-elantra-2025-1.jpg",
            "images/cars/hyundai-elantra-2025/hyundai-elantra-2025-2.jpg",
            "images/cars/hyundai-elantra-2025/hyundai-elantra-2025-3.jpg",
            "images/cars/hyundai-elantra-2025/hyundai-elantra-2025-4.jpg",
            "images/cars/hyundai-elantra-2025/hyundai-elantra-2025-5.jpg",
            "images/cars/hyundai-elantra-2025/hyundai-elantra-2025-6.jpg",
            "images/cars/hyundai-elantra-2025/hyundai-elantra-2025-7.jpg",
            "images/cars/hyundai-elantra-2025/hyundai-elantra-2025-8.jpg"
        ]
    },
    {
        "id": "geely-coolray-2026",
        "brand": "Geely",
        "model": "Coolray",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 122,
        "transmission": "Робот / CVT",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 1790000,
        "priceIsFrom": true,
        "features": [
            "2 комплектации на выбор",
            "Super — 1 790 000 ₽: робот DSG, кожаные сиденья, камера зад. вида, круиз-контроль, экран 8\", Bluetooth",
            "Max — 1 890 000 ₽: CVT автомат, панорамный люк, кожаный руль, экран 12,3\", электропривод сиденья, задние парктроники"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/geely-coolray-2026/geely-coolray-2026-1.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-2.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-3.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-4.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-5.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-6.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-7.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-8.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-9.jpg",
            "images/cars/geely-coolray-2026/geely-coolray-2026-10.jpg"
        ]
    },
    {
        "id": "kia-kx1-2026",
        "brand": "Kia",
        "model": "KX1",
        "year": 2026,
        "engineVolume": 1.4,
        "horsePower": 100,
        "transmission": "Автомат (CVT)",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 1735000,
        "priceIsFrom": true,
        "features": [
            "2 комплектации на выбор",
            "Comfort — 1 735 000 ₽: климат-контроль, LED фары, камера зад. вида, ЖК-экран, подогрев сидений",
            "Luxury — 1 885 000 ₽: кожаный салон, панорамная крыша, бесключевой доступ, электропривод сидений, парктроники 360°"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-1.jpg",
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-2.jpg",
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-3.jpg",
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-4.jpg",
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-5.jpg",
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-6.jpg",
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-7.jpg",
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-8.jpg",
            "images/cars/Kia-kx1-2026/Kia-kx1-2026-9.jpg"
        ]
    },
    {
        "id": "volkswagen-t-roc-2026",
        "brand": "Volkswagen",
        "model": "T-Roc",
        "year": 2026,
        "engineVolume": 1.4,
        "horsePower": 150,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2590000,
        "features": [
            "Цена под ключ · Новый",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Парктроники",
            "Бесключевой доступ · Кожаный руль",
            "Сенсорный экран 10\" · Круиз-контроль",
            "Электрорегулировка зеркал"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-1.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-2.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-3.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-4.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-5.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-6.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-7.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-8.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-9.jpg",
            "images/cars/Volkswagen-T-roc-2026/Volkswagen-T-roc-2026-10.jpg"
        ]
    },
    {
        "id": "audi-a5-2026",
        "brand": "Audi",
        "model": "A5",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 204,
        "transmission": "Робот",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 5660000,
        "priceIsFrom": true,
        "features": [
            "Премиум люкс · Новинка 2026",
            "Matrix LED фары · Панорамная крыша",
            "Кожаный салон Nappa · Вентиляция сидений",
            "Bang & Olufsen аудиосистема",
            "Виртуальная приборная панель 12,3\"",
            "Адаптивный круиз-контроль · Камера 360°",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/AUDI-A5-2026/AUDI-A5-2026-1.jpg",
            "images/cars/AUDI-A5-2026/AUDI-A5-2026-2.jpg",
            "images/cars/AUDI-A5-2026/AUDI-A5-2026-3.jpg",
            "images/cars/AUDI-A5-2026/AUDI-A5-2026-4.jpg",
            "images/cars/AUDI-A5-2026/AUDI-A5-2026-5.jpg"
        ],
        "tags": [
            "Премиум люкс",
            "Новинка"
        ]
    },
    {
        "id": "toyota-rav4-2026",
        "brand": "Toyota",
        "model": "RAV-4",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 171,
        "transmission": "Вариатор (CVT)",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 3990000,
        "features": [
            "Комплектация Adventure Plus · Полный привод 4WD",
            "Кожаный салон · Климат-контроль",
            "Камера 360° · LED фары",
            "Адаптивный круиз-контроль Toyota Safety Sense",
            "Бесключевой доступ · Электропривод багажника",
            "Подогрев передних сидений · 18\" диски",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Toyota-Rav-4/Toyota-Rav-4-1.jpg",
            "images/cars/Toyota-Rav-4/Toyota-Rav-4-2.jpg",
            "images/cars/Toyota-Rav-4/Toyota-Rav-4-3.jpg",
            "images/cars/Toyota-Rav-4/Toyota-Rav-4-4.jpg",
            "images/cars/Toyota-Rav-4/Toyota-Rav-4-5.jpg",
            "images/cars/Toyota-Rav-4/Toyota-Rav-4-6.jpg",
            "images/cars/Toyota-Rav-4/Toyota-Rav-4-7.jpg",
            "images/cars/Toyota-Rav-4/Toyota-Rav-4-8.jpg"
        ]
    },
    {
        "id": "toyota-haylender-2026",
        "brand": "Toyota",
        "model": "Highlander",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 248,
        "transmission": "Автомат",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 5320000,
        "features": [
            "7 мест · Максимальная комплектация · Полный привод",
            "Кожаный салон · Трёхзонный климат-контроль",
            "Панорамная крыша · Электропривод 2-го ряда",
            "Камера 360° · Адаптивный круиз-контроль",
            "Бесключевой доступ · JBL аудиосистема",
            "Подогрев всех сидений · Вентиляция 1-го ряда",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-1.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-2.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-3.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-4.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-5.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-6.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-7.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-8.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-9.jpg",
            "images/cars/Toyota-Haylender-2026/Toyota-Haylender-2026-10.jpg"
        ]
    },
    {
        "id": "volkswagen-tharu-xr-2026",
        "brand": "Volkswagen",
        "model": "Tharu XR",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 110,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2137000,
        "priceIsFrom": true,
        "features": [
            "Цена под ключ · Новый",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Парктроники",
            "Адаптивный круиз-контроль",
            "Бесключевой доступ · Кожаный руль",
            "Сенсорный экран · Подогрев сидений"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-1.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-2.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-3.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-4.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-5.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-6.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-7.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-8.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-9.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-10.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-11.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-12.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-13.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-14.jpg",
            "images/cars/Volkswagen-Tharu-XR-2026/Volkswagen-Tharu-XR-2026-15.jpg"
        ]
    },
    {
        "id": "kia-k3-2026",
        "brand": "Kia",
        "model": "K3",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 115,
        "transmission": "Вариатор (CVT)",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2054000,
        "priceIsFrom": true,
        "features": [
            "2 комплектации на выбор",
            "Comfort — 2 054 000 ₽: LED фары, климат-контроль, камера зад. вида, ЖК-экран, подогрев сидений",
            "Prestige — 2 230 000 ₽: кожаный салон, панорамная крыша, бесключевой доступ, камера 360°, вентиляция сидений"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Киак-3/Киа-к3-1.jpg",
            "images/cars/Киак-3/Киа-к3-2.jpg",
            "images/cars/Киак-3/Киа-к3-3.jpg",
            "images/cars/Киак-3/Киа-к3-4.jpg",
            "images/cars/Киак-3/Киа-к3-5.jpg",
            "images/cars/Киак-3/Киа-к3-6.jpg",
            "images/cars/Киак-3/Киа-к3-7.jpg",
            "images/cars/Киак-3/Киа-к3-8.jpg",
            "images/cars/Киак-3/Киа-к3-9.jpg",
            "images/cars/Киак-3/Киа-к3-10.jpg",
            "images/cars/Киак-3/Киа-к3-11.jpg",
            "images/cars/Киак-3/Киа-к3-12.jpg"
        ]
    },
    {
        "id": "mazda-cx50-2026",
        "brand": "Mazda",
        "model": "CX-50",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 155,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 3370000,
        "features": [
            "Цена под ключ · Новый",
            "Климат-контроль · LED фары",
            "Кожаный салон · Бесключевой доступ",
            "Камера 360° · Адаптивный круиз-контроль",
            "Подогрев сидений · Электропривод багажника",
            "ЖК-экран 10,25\" · Парктроники"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Mazda-CX-50/Mazda-CX-50-1.jpg",
            "images/cars/Mazda-CX-50/Mazda-CX-50-2.jpg",
            "images/cars/Mazda-CX-50/Mazda-CX-50-3.jpg",
            "images/cars/Mazda-CX-50/Mazda-CX-50-4.jpg",
            "images/cars/Mazda-CX-50/Mazda-CX-50-5.jpg",
            "images/cars/Mazda-CX-50/Mazda-CX-50-6.jpg",
            "images/cars/Mazda-CX-50/Mazda-CX-50-7.jpg",
            "images/cars/Mazda-CX-50/Mazda-CX-50-8.jpg"
        ]
    },
    {
        "id": "volkswagen-tiguan-l-pro-2026",
        "brand": "Volkswagen",
        "model": "Tiguan L Pro",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 220,
        "transmission": "Автомат",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 4690000,
        "features": [
            "R-Line пакет · Полный привод 4MOTION",
            "Кожаный салон · Трёхзонный климат-контроль",
            "Панорамная крыша · Камера 360°",
            "Адаптивный круиз-контроль",
            "Сенсорный экран 12\" · LED матричные фары",
            "Бесключевой доступ · Электропривод багажника",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-1.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-2.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-3.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-4.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-5.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-6.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-7.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-8.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-9.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-10.jpg",
            "images/cars/Volkswagen-Tiguan-L-pro/Volkswagen-Tiguan-L-pro-11.jpg"
        ]
    },
    {
        "id": "volkswagen-teramont-pro-2026",
        "brand": "Volkswagen",
        "model": "Teramont Pro",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 272,
        "transmission": "Автомат",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 5866000,
        "features": [
            "Discovery Edition · Полный привод 4MOTION",
            "7 мест · Панорамная крыша",
            "Кожаный салон · Трёхзонный климат-контроль",
            "LED матричные фары · Камера 360°",
            "Адаптивный круиз-контроль · Harman Kardon",
            "Бесключевой доступ · Электропривод багажника",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-1.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-2.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-3.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-4.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-5.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-6.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-7.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-8.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-9.jpg",
            "images/cars/VOLKSWAGEN-Teramont-Pro/VOLKSWAGEN-Teramont-Pro-10.jpg"
        ]
    },
    {
        "id": "kia-seltos-korea-2021",
        "brand": "Kia",
        "model": "Seltos",
        "year": 2021,
        "engineVolume": 1.6,
        "horsePower": 136,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 48000,
        "price": 2100000,
        "features": [
            "Климат-контроль · LED фары",
            "Кожаный руль · Камера заднего вида",
            "Круиз-контроль · Подогрев сидений",
            "Бесключевой доступ · ЖК-экран",
            "Пробег 48 000 км · Корея"
        ],
        "location": "Корея",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/KIA-Seltos/KIA-Seltos-1.jpg",
            "images/cars/KIA-Seltos/KIA-Seltos-2.jpg",
            "images/cars/KIA-Seltos/KIA-Seltos-3.jpg",
            "images/cars/KIA-Seltos/KIA-Seltos-4.jpg",
            "images/cars/KIA-Seltos/KIA-Seltos-5.jpg",
            "images/cars/KIA-Seltos/KIA-Seltos-6.jpg"
        ],
        "tags": [
            "Компактный кроссовер",
            "Экономичный"
        ]
    },
    {
        "id": "hyundai-sonata-2023",
        "brand": "Hyundai",
        "model": "Sonata",
        "year": 2023,
        "engineVolume": 2,
        "horsePower": 159,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 43000,
        "price": 3090000,
        "features": [
            "Бизнес-класс · Корейская сборка",
            "Кожаный салон · Климат-контроль",
            "Панорамная крыша · LED фары",
            "Камера 360° · Адаптивный круиз-контроль",
            "Бесключевой доступ · Подогрев сидений",
            "Пробег 43 000 км"
        ],
        "location": "Корея",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Hyundai-Sonata/Hyundai-Sonata-1.jpg",
            "images/cars/Hyundai-Sonata/Hyundai-Sonata-2.jpg",
            "images/cars/Hyundai-Sonata/Hyundai-Sonata-3.jpg",
            "images/cars/Hyundai-Sonata/Hyundai-Sonata-4.jpg",
            "images/cars/Hyundai-Sonata/Hyundai-Sonata-5.jpg",
            "images/cars/Hyundai-Sonata/Hyundai-Sonata-6.jpg"
        ],
        "tags": [
            "Бизнес-класс",
            "Стильный"
        ]
    },
    {
        "id": "kia-k5-korea-2023",
        "brand": "Kia",
        "model": "K5",
        "year": 2023,
        "engineVolume": 2,
        "horsePower": 160,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 23800,
        "price": 2750000,
        "features": [
            "Спортивный седан · Корейская сборка",
            "Кожаный салон · Климат-контроль",
            "LED фары · Камера заднего вида",
            "Адаптивный круиз-контроль",
            "Бесключевой доступ · Подогрев сидений",
            "Пробег 23 800 км"
        ],
        "location": "Корея",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/KIA-K5/KIA-K5-1.jpg",
            "images/cars/KIA-K5/KIA-K5-2.jpg",
            "images/cars/KIA-K5/KIA-K5-3.jpg",
            "images/cars/KIA-K5/KIA-K5-4.jpg",
            "images/cars/KIA-K5/KIA-K5-5.jpg",
            "images/cars/KIA-K5/KIA-K5-6.jpg"
        ],
        "tags": [
            "Спортивный дизайн",
            "Современный"
        ]
    },
    {
        "id": "honda-vezel-2023",
        "brand": "Honda",
        "model": "Vezel",
        "year": 2023,
        "engineVolume": 1.5,
        "horsePower": 124,
        "transmission": "Вариатор (CVT)",
        "drivetrain": "Передний привод",
        "mileage": 15000,
        "price": 1990000,
        "features": [
            "Гибридная система · Малый расход топлива",
            "Климат-контроль · LED фары",
            "Камера заднего вида · ЖК-экран",
            "Круиз-контроль · Подогрев сидений",
            "Бесключевой доступ · Пробег 15 000 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Honda-Vezel/Honda-Vezel-1.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-2.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-3.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-4.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-5.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-6.jpg"
        ],
        "tags": [
            "Надёжный",
            "Малый расход"
        ]
    },
    {
        "id": "volkswagen-touran-l-2022",
        "brand": "Volkswagen",
        "model": "Touran L",
        "year": 2022,
        "engineVolume": 1.4,
        "horsePower": 150,
        "transmission": "Робот (DSG)",
        "drivetrain": "Передний привод",
        "mileage": 5000,
        "price": 2390000,
        "features": [
            "7 мест · Семейный минивэн",
            "Климат-контроль · LED фары",
            "Кожаный руль · Камера заднего вида",
            "Адаптивный круиз-контроль · Парктроники",
            "Бесключевой доступ · Пробег 5 000 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Volkswagen-Touran-L-280TSI-DSG/Volkswagen-Touran-L-280TSI-DSG-1.jpg",
            "images/cars/Volkswagen-Touran-L-280TSI-DSG/Volkswagen-Touran-L-280TSI-DSG-2.jpg",
            "images/cars/Volkswagen-Touran-L-280TSI-DSG/Volkswagen-Touran-L-280TSI-DSG-3.jpg",
            "images/cars/Volkswagen-Touran-L-280TSI-DSG/Volkswagen-Touran-L-280TSI-DSG-4.jpg",
            "images/cars/Volkswagen-Touran-L-280TSI-DSG/Volkswagen-Touran-L-280TSI-DSG-5.jpg",
            "images/cars/Volkswagen-Touran-L-280TSI-DSG/Volkswagen-Touran-L-280TSI-DSG-6.jpg",
            "images/cars/Volkswagen-Touran-L-280TSI-DSG/Volkswagen-Touran-L-280TSI-DSG-7.jpg"
        ],
        "tags": [
            "Семейный",
            "7 мест"
        ]
    },
    {
        "id": "mini-countryman-cooper-2022",
        "brand": "Mini",
        "model": "Countryman Cooper",
        "year": 2022,
        "engineVolume": 1.5,
        "horsePower": 136,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 37000,
        "price": 2590000,
        "features": [
            "Iconic британский дизайн",
            "Кожаный салон · Панорамная крыша",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Парктроники",
            "Бесключевой доступ · Подогрев сидений",
            "Пробег 37 000 км · Корея"
        ],
        "location": "Корея",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Mini-Countryman-Cooper/Mini-Countryman-Cooper-1.jpg",
            "images/cars/Mini-Countryman-Cooper/Mini-Countryman-Cooper-2.jpg",
            "images/cars/Mini-Countryman-Cooper/Mini-Countryman-Cooper-3.jpg",
            "images/cars/Mini-Countryman-Cooper/Mini-Countryman-Cooper-4.jpg",
            "images/cars/Mini-Countryman-Cooper/Mini-Countryman-Cooper-5.jpg",
            "images/cars/Mini-Countryman-Cooper/Mini-Countryman-Cooper-6.jpg"
        ],
        "tags": [
            "Британский стиль",
            "Харизматичный"
        ]
    },
    {
        "id": "hyundai-tucson-2026",
        "brand": "Hyundai",
        "model": "Tucson",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 200,
        "transmission": "Автомат",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 3790000,
        "features": [
            "Максимальная комплектация · Полный привод",
            "Кожаный салон · Трёхзонный климат-контроль",
            "Панорамная крыша · LED матричные фары",
            "Камера 360° · Адаптивный круиз-контроль",
            "Бесключевой доступ · Вентиляция сидений",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-1.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-2.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-3.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-4.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-5.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-6.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-7.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-8.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-9.jpg",
            "images/cars/Hyundai-Tucson/Hyundai-Tucson-10.jpg"
        ],
        "tags": [
            "Макс. комплектация",
            "Хит продаж"
        ]
    },
    {
        "id": "audi-a5l-2026",
        "brand": "Audi",
        "model": "A5L",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 204,
        "transmission": "Робот",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 5680000,
        "features": [
            "Премиум · Длиннобазная версия A5L",
            "Matrix LED фары · Панорамная крыша",
            "Кожаный салон Nappa · Вентиляция сидений",
            "Bang & Olufsen аудиосистема · Камера 360°",
            "Виртуальная приборная панель 12,3\"",
            "Адаптивный круиз-контроль · Полный привод",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/AUDI-A5L/AUDI-A5L-1.jpg",
            "images/cars/AUDI-A5L/AUDI-A5L-2.jpg",
            "images/cars/AUDI-A5L/AUDI-A5L-3.jpg",
            "images/cars/AUDI-A5L/AUDI-A5L-4.jpg",
            "images/cars/AUDI-A5L/AUDI-A5L-5.jpg",
            "images/cars/AUDI-A5L/AUDI-A5L-6.jpg"
        ],
        "tags": [
            "Премиум люкс",
            "Новинка"
        ]
    },
    {
        "id": "lexus-nx200-2025",
        "brand": "Lexus",
        "model": "NX200",
        "year": 2025,
        "engineVolume": 2,
        "horsePower": 173,
        "transmission": "Вариатор",
        "drivetrain": "Передний привод",
        "mileage": 4000,
        "price": 5690000,
        "features": [
            "Японский премиум · Люксовый SUV",
            "Кожаный салон · Климат-контроль",
            "LED фары · Панорамная крыша",
            "Камера 360° · Адаптивный круиз-контроль",
            "Бесключевой доступ · Mark Levinson аудио",
            "Пробег 4 000 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Lexus-NX200/Lexus-NX200-1.jpg",
            "images/cars/Lexus-NX200/Lexus-NX200-2.jpg",
            "images/cars/Lexus-NX200/Lexus-NX200-3.jpg",
            "images/cars/Lexus-NX200/Lexus-NX200-4.jpg",
            "images/cars/Lexus-NX200/Lexus-NX200-5.jpg",
            "images/cars/Lexus-NX200/Lexus-NX200-6.jpg"
        ],
        "tags": [
            "Премиум",
            "Высокая надёжность"
        ]
    },
    {
        "id": "toyota-bz3x-2025",
        "brand": "Toyota",
        "model": "bZ3X",
        "year": 2025,
        "engineVolume": 0,
        "horsePower": 204,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 3290000,
        "features": [
            "Электромобиль · Запас хода 615 км",
            "Кожаный салон · Климат-контроль",
            "Панорамная крыша · LED фары",
            "Камера 360° · Быстрая зарядка",
            "Адаптивный круиз-контроль",
            "Бесключевой доступ · Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-1.jpg",
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-2.jpg",
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-3.jpg",
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-4.jpg",
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-5.jpg",
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-6.jpg",
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-7.jpg",
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-8.jpg",
            "images/cars/Toyota-bZ3X/Toyota-bZ3X-9.jpg"
        ],
        "tags": [
            "Электро",
            "Выгодный заказ"
        ]
    },
    {
        "id": "benda-lfc-700-pro-2026",
        "brand": "Benda",
        "model": "LFC 700 pro",
        "year": 2026,
        "engineVolume": 0.7,
        "horsePower": 78,
        "transmission": "Механика",
        "drivetrain": "Задний привод",
        "mileage": 0,
        "price": 980000,
        "features": [
            "Ретро-круизер · Объём 700 см³",
            "Жидкостное охлаждение · Инжектор",
            "6-ступенчатая КПП · Задний привод",
            "Цифровая приборная панель",
            "ABS · Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Benda-LFC-700-pro/Benda-LFC-700-pro-1.jpg",
            "images/cars/Benda-LFC-700-pro/Benda-LFC-700-pro-2.jpg",
            "images/cars/Benda-LFC-700-pro/Benda-LFC-700-pro-3.jpg"
        ],
        "tags": [
            "Мотоцикл",
            "Уникальный дизайн"
        ]
    },
    {
        "id": "hyundai-santa-fe-2026",
        "brand": "Hyundai",
        "model": "Santa Fe",
        "year": 2026,
        "engineVolume": 2.5,
        "horsePower": 281,
        "transmission": "Автомат",
        "drivetrain": "Полный привод",
        "mileage": 3000,
        "price": 7115000,
        "features": [
            "Calligraphy · Флагманская комплектация",
            "3 ряда сидений · 7 мест",
            "Кожаный салон Nappa · Вентиляция всех рядов",
            "Панорамная крыша · LED матричные фары",
            "Камера 360° · Bose аудиосистема (12 колонок)",
            "Адаптивный круиз-контроль · Полный привод",
            "Пробег 3 000 км · Корея"
        ],
        "location": "Корея",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Hyundai-Santa-Fe/Hyundai-Santa-Fe-1.jpg",
            "images/cars/Hyundai-Santa-Fe/Hyundai-Santa-Fe-2.jpg",
            "images/cars/Hyundai-Santa-Fe/Hyundai-Santa-Fe-3.jpg",
            "images/cars/Hyundai-Santa-Fe/Hyundai-Santa-Fe-4.jpg",
            "images/cars/Hyundai-Santa-Fe/Hyundai-Santa-Fe-5.jpg",
            "images/cars/Hyundai-Santa-Fe/Hyundai-Santa-Fe-6.jpg",
            "images/cars/Hyundai-Santa-Fe/Hyundai-Santa-Fe-7.jpg",
            "images/cars/Hyundai-Santa-Fe/Hyundai-Santa-Fe-8.jpg"
        ],
        "tags": [
            "Calligraphy",
            "Третий ряд сидений"
        ]
    },
    {
        "id": "changan-uni-s-2026",
        "brand": "Changan",
        "model": "UNI-S",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 181,
        "transmission": "Робот",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 2950000,
        "features": [
            "Полный привод AWD · Турбо 181 л.с.",
            "Кожаный салон · Климат-контроль",
            "Панорамная крыша · LED фары",
            "Камера 360° · Адаптивный круиз-контроль",
            "Бесключевой доступ · Сенсорный экран 14.6\"",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Changan-UNI-S/Changan-UNI-S-1.jpg",
            "images/cars/Changan-UNI-S/Changan-UNI-S-2.jpg",
            "images/cars/Changan-UNI-S/Changan-UNI-S-3.jpg",
            "images/cars/Changan-UNI-S/Changan-UNI-S-4.jpg",
            "images/cars/Changan-UNI-S/Changan-UNI-S-5.jpg",
            "images/cars/Changan-UNI-S/Changan-UNI-S-6.jpg"
        ],
        "tags": [
            "Современный",
            "Полный привод"
        ]
    },
    {
        "id": "kia-sportage-2026",
        "brand": "Kia",
        "model": "Sportage",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 200,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 3690000,
        "features": [
            "Максимальная комплектация · 200 л.с.",
            "Кожаный салон · Климат-контроль",
            "Панорамная крыша · LED фары",
            "Камера 360° · Адаптивный круиз-контроль",
            "Бесключевой доступ · Подогрев/вентиляция сидений",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/KIA-Sportage/KIA-Sportage-1.jpg",
            "images/cars/KIA-Sportage/KIA-Sportage-2.jpg",
            "images/cars/KIA-Sportage/KIA-Sportage-3.jpg",
            "images/cars/KIA-Sportage/KIA-Sportage-4.jpg",
            "images/cars/KIA-Sportage/KIA-Sportage-5.jpg",
            "images/cars/KIA-Sportage/KIA-Sportage-6.jpg"
        ],
        "tags": [
            "Надежный кроссовер",
            "Топовый дизайн"
        ]
    },
    {
        "id": "geely-galaxy-starship-7-2026",
        "brand": "Geely",
        "model": "Galaxy Starship 7",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 238,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 3740000,
        "features": [
            "Гибрид PHEV · 238 л.с. · Запас хода 1200 км",
            "Кожаный салон · Климат-контроль",
            "Панорамная крыша · LED фары",
            "Камера 360° · Адаптивный круиз-контроль",
            "Сенсорный экран 13,2\" · Бесключевой доступ",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Geely-Galaxy-Starship-7/Geely-Galaxy-Starship-7-1.jpg",
            "images/cars/Geely-Galaxy-Starship-7/Geely-Galaxy-Starship-7-2.jpg",
            "images/cars/Geely-Galaxy-Starship-7/Geely-Galaxy-Starship-7-3.jpg",
            "images/cars/Geely-Galaxy-Starship-7/Geely-Galaxy-Starship-7-4.jpg",
            "images/cars/Geely-Galaxy-Starship-7/Geely-Galaxy-Starship-7-5.jpg",
            "images/cars/Geely-Galaxy-Starship-7/Geely-Galaxy-Starship-7-6.jpg"
        ],
        "tags": [
            "Гибрид",
            "Инновационный"
        ]
    },
    {
        "id": "toyota-camry-2026",
        "brand": "Toyota",
        "model": "Camry",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 173,
        "transmission": "Вариатор",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 3790000,
        "features": [
            "Бизнес-класс · Японское качество",
            "Кожаный салон · Климат-контроль",
            "LED фары · Камера 360°",
            "Адаптивный круиз-контроль",
            "Бесключевой доступ · Подогрев сидений",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Toyota-Camry/Toyota-Camry-1.jpg",
            "images/cars/Toyota-Camry/Toyota-Camry-2.jpg",
            "images/cars/Toyota-Camry/Toyota-Camry-3.jpg",
            "images/cars/Toyota-Camry/Toyota-Camry-4.jpg"
        ],
        "tags": [
            "Легенда",
            "Бизнес-класс"
        ]
    },
    {
        "id": "geely-monjaro-2026",
        "brand": "Geely",
        "model": "Monjaro",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 272,
        "transmission": "Автомат",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 4050000,
        "features": [
            "Флагман · Максимальная комплектация",
            "Полный привод AWD · 272 л.с.",
            "Кожаный салон · Трёхзонный климат-контроль",
            "Панорамная крыша · LED фары",
            "Камера 360° · Adаптивный круиз-контроль",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Geely-Monjaro/Geely-Monjaro-1.jpg",
            "images/cars/Geely-Monjaro/Geely-Monjaro-2.jpg",
            "images/cars/Geely-Monjaro/Geely-Monjaro-3.jpg"
        ],
        "tags": [
            "Флагман",
            "Макс. комплектация"
        ]
    },
    {
        "id": "volkswagen-sagitar-2022",
        "brand": "Volkswagen",
        "model": "Sagitar",
        "year": 2022,
        "engineVolume": 1.4,
        "horsePower": 149,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 56000,
        "price": 1950000,
        "features": [
            "Турбо 1.4 · Заводской окрас",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Парктроники",
            "Круиз-контроль · Подогрев сидений",
            "Пробег 56 000 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Volkswagen-Sagitar-2022/Volkswagen-Sagitar-2022-1.jpg",
            "images/cars/Volkswagen-Sagitar-2022/Volkswagen-Sagitar-2022-2.jpg",
            "images/cars/Volkswagen-Sagitar-2022/Volkswagen-Sagitar-2022-3.jpg",
            "images/cars/Volkswagen-Sagitar-2022/Volkswagen-Sagitar-2022-4.jpg",
            "images/cars/Volkswagen-Sagitar-2022/Volkswagen-Sagitar-2022-5.jpg"
        ],
        "tags": [
            "Заводской окрас",
            "Турбо"
        ]
    },
    {
        "id": "kia-morning-2023",
        "brand": "Kia",
        "model": "Morning",
        "year": 2023,
        "engineVolume": 1,
        "horsePower": 76,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 23200,
        "price": 1690000,
        "features": [
            "Городской автомобиль · Корея",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Подогрев сидений · ЖК-экран",
            "Пробег 23 200 км"
        ],
        "location": "Корея",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/KIA-MORNING/KIA-MORNING-1.jpg",
            "images/cars/KIA-MORNING/KIA-MORNING-2.jpg",
            "images/cars/KIA-MORNING/KIA-MORNING-3.jpg",
            "images/cars/KIA-MORNING/KIA-MORNING-4.jpg",
            "images/cars/KIA-MORNING/KIA-MORNING-5.jpg",
            "images/cars/KIA-MORNING/KIA-MORNING-6.jpg"
        ],
        "tags": [
            "Для города",
            "Компакт"
        ]
    },
    {
        "id": "hyundai-venue-2024",
        "brand": "Hyundai",
        "model": "Venue",
        "year": 2024,
        "engineVolume": 1.6,
        "horsePower": 121,
        "transmission": "Вариатор",
        "drivetrain": "Передний привод",
        "mileage": 9900,
        "price": 2190000,
        "features": [
            "Компактный SUV · Корея",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Подогрев сидений · Бесключевой доступ",
            "Пробег 9 900 км"
        ],
        "location": "Корея",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Hyundai-Venue/Hyundai-Venue-1.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-2.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-3.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-4.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-5.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-6.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-7.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-8.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-9.jpg",
            "images/cars/Hyundai-Venue/Hyundai-Venue-10.jpg"
        ],
        "tags": [
            "Компактный",
            "В наличии"
        ]
    },
    {
        "id": "zeekr-8x-2026",
        "brand": "Zeekr",
        "model": "8X",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 898,
        "transmission": "Автомат",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 10890000,
        "features": [
            "Гибрид PHEV · 898 л.с. · Полный привод",
            "Кожаный салон Nappa · Четырёхзонный климат",
            "Панорамная крыша · Матричные LED фары",
            "Камера 360° · HUD · 23 динамика Dynaudio",
            "Адаптивный круиз-контроль L3",
            "Разгон 0–100 км/ч за 3,5 с · Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Zeekr-8X/Zeekr-8X-1.jpg",
            "images/cars/Zeekr-8X/Zeekr-8X-2.jpg",
            "images/cars/Zeekr-8X/Zeekr-8X-3.jpg",
            "images/cars/Zeekr-8X/Zeekr-8X-4.jpg"
        ],
        "description": "2026 | 2.0 898 л.с. | гибрид | автомат | полный привод\nНОВЫЙ В ЧЕРНОМ ЦВЕТЕ"
    },
    {
        "id": "changan-qiyuan-q05-2025",
        "brand": "Changan",
        "model": "Qiyuan Q05",
        "year": 2025,
        "engineVolume": "Электро",
        "horsePower": 163,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 8800,
        "price": 2590000,
        "features": [
            "Электромобиль · Запас хода 215 км",
            "Кожаный салон · Вентиляция/массаж сидений",
            "Климат-контроль · Камера 360° · HUD",
            "AEB · Адаптивный круиз-контроль L2",
            "Электропривод багажника · Бесключевой доступ",
            "Пробег 8 800 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-1.jpg",
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-2.jpg",
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-3.jpg",
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-4.jpg",
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-5.jpg",
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-6.jpg",
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-7.jpg",
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-8.jpg",
            "images/cars/Changan-Qiyuan-Q05/Changan-Qiyuan-Q05-9.jpg"
        ],
        "description": "2025 | электро 163 л.с. | 2WD | Заводской окрас, запас хода 215 км, пробег 8.8 тыс км.\n\nКомплектация:\n- Система предупреждения о сходе с полосы и автоматического экстренного торможения (AEB)\n- Режим охраны Sentry Mode\n- Камера кругового обзора 360° и контроль слепых зон\n- Адаптивный круиз-контроль (L2), удержание и центрирование в полосе\n- Электропривод багажника, бесключевой доступ\n- Кожаный салон, электрорегулировка, подогрев, вентиляция и массаж передних сидений\n- Автоматический климат-контроль"
    },
    {
        "id": "skoda-superb-2021",
        "brand": "Skoda",
        "model": "Superb",
        "year": 2021,
        "engineVolume": 1.4,
        "horsePower": 150,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 34800,
        "price": 2290000,
        "features": [
            "TSI280 DSG Comfort · Просторный лифтбек",
            "Кожаный салон · Климат-контроль",
            "Люк · Камера заднего вида · Парктроники",
            "Адаптивный круиз-контроль · Автопарковка",
            "Бесключевой доступ · Электропривод багажника",
            "Пробег 34 800 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Skoda-Superb/Skoda-Superb-1.jpg",
            "images/cars/Skoda-Superb/Skoda-Superb-2.jpg",
            "images/cars/Skoda-Superb/Skoda-Superb-3.jpg",
            "images/cars/Skoda-Superb/Skoda-Superb-4.jpg",
            "images/cars/Skoda-Superb/Skoda-Superb-5.jpg",
            "images/cars/Skoda-Superb/Skoda-Superb-6.jpg",
            "images/cars/Skoda-Superb/Skoda-Superb-7.jpg",
            "images/cars/Skoda-Superb/Skoda-Superb-8.jpg",
            "images/cars/Skoda-Superb/Skoda-Superb-9.jpg"
        ],
        "description": "2021 | 1.4 бензин 150 л.с. | робот | 2WD\nПробег: 34,8 тыс км\n\nКомплектация TSI280 DSG Comfort:\n- Система контроля усталости водителя и Auto Hold\n- Передние и задние парктроники, камера заднего вида\n- Круиз-контроль, система автоматической парковки\n- Запуск двигателя кнопкой (Start/Stop) и бесключевой доступ\n- Электрический люк\n- Электрорегулировка и подогрев наружных зеркал\n- Многофункциональное рулевое колесо и кожаный салон\n- Электрорегулировка водительского сиденья и подогрев передних сидений\n- Электропривод крышки багажника"
    },
    {
        "id": "toyota-yaris-l-2022",
        "brand": "Toyota",
        "model": "YARiS L",
        "year": 2022,
        "engineVolume": 1.5,
        "horsePower": 111,
        "transmission": "Вариатор (CVT)",
        "drivetrain": "Передний привод",
        "mileage": 41000,
        "price": 1690000,
        "features": [
            "Luxury PLUS Edition · Японская сборка",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Подогрев сидений · ЖК-экран",
            "Пробег 41 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Toyota-YARiS-L/Toyota-YARiS-L-1.jpg",
            "images/cars/Toyota-YARiS-L/Toyota-YARiS-L-2.jpg",
            "images/cars/Toyota-YARiS-L/Toyota-YARiS-L-3.jpg",
            "images/cars/Toyota-YARiS-L/Toyota-YARiS-L-4.jpg",
            "images/cars/Toyota-YARiS-L/Toyota-YARiS-L-5.jpg",
            "images/cars/Toyota-YARiS-L/Toyota-YARiS-L-6.jpg",
            "images/cars/Toyota-YARiS-L/Toyota-YARiS-L-7.jpg",
            "images/cars/Toyota-YARiS-L/Toyota-YARiS-L-8.jpg"
        ],
        "description": "2022 | 1.5 111 л.с. | CVT | 2WD\nКомплектация: Luxury PLUS Edition\nЗаводской окрас\nПробег: 41 000 км\n\nСтоимость авто в юанях: 78 800"
    },
    {
        "id": "bmw-x1-2023",
        "brand": "BMW",
        "model": "X1",
        "year": 2023,
        "engineVolume": 2.0,
        "horsePower": 140,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 40000,
        "price": 3190000,
        "features": [
            "Городской премиум · BMW качество",
            "Кожаный руль · Климат-контроль",
            "LED фары · Камера заднего вида",
            "Круиз-контроль · Парктроники",
            "Пробег 40 000 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/BMW-x1/BMW-x1-1.jpg",
            "images/cars/BMW-x1/BMW-x1-2.jpg",
            "images/cars/BMW-x1/BMW-x1-3.jpg",
            "images/cars/BMW-x1/BMW-x1-4.jpg",
            "images/cars/BMW-x1/BMW-x1-5.jpg",
            "images/cars/BMW-x1/BMW-x1-6.jpg",
            "images/cars/BMW-x1/BMW-x1-7.jpg"
        ],
        "description": "BMW X1 2023 года — компактный премиальный кроссовер с классическим немецким характером. Двигатель 2.0 л мощностью 140 л.с. в связке с автоматической трансмиссией обеспечивает уверенную динамику в городском потоке и за его пределами. Стильный экстерьер, высококачественный интерьер и надёжная инженерия BMW — всё это в одном автомобиле. Итоговая стоимость с учетом всех расходов: 3 190 000 ₽."
    },
    {
        "id": "skoda-kamiq-2023",
        "brand": "Skoda",
        "model": "Kamiq",
        "year": 2023,
        "engineVolume": 1.5,
        "horsePower": 109,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 12000,
        "price": 2250000,
        "features": [
            "Городской кроссовер · Чешское качество",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Подогрев сидений · Парктроники",
            "Пробег 12 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Skoda-Kamiq/Skoda-Kamiq-1.jpg",
            "images/cars/Skoda-Kamiq/Skoda-Kamiq-2.jpg",
            "images/cars/Skoda-Kamiq/Skoda-Kamiq-3.jpg",
            "images/cars/Skoda-Kamiq/Skoda-Kamiq-4.jpg",
            "images/cars/Skoda-Kamiq/Skoda-Kamiq-5.jpg",
            "images/cars/Skoda-Kamiq/Skoda-Kamiq-6.jpg",
            "images/cars/Skoda-Kamiq/Skoda-Kamiq-7.jpg"
        ],
        "description": "Компактный кроссовер из Китая с пробегом. Заводской окрас кузова, отличное состояние."
    },
    {
        "id": "toyota-corolla-2022",
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2022,
        "engineVolume": 1.2,
        "horsePower": 116,
        "transmission": "Вариатор",
        "drivetrain": "Передний привод",
        "mileage": 35000,
        "price": 1990000,
        "features": [
            "Японская надёжность · Экономичный",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Подогрев сидений · ЖК-экран",
            "Пробег 35 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Toyota-Corolla/Toyota-Corolla-1.jpg",
            "images/cars/Toyota-Corolla/Toyota-Corolla-2.jpg",
            "images/cars/Toyota-Corolla/Toyota-Corolla-3.jpg",
            "images/cars/Toyota-Corolla/Toyota-Corolla-4.jpg",
            "images/cars/Toyota-Corolla/Toyota-Corolla-5.jpg"
        ],
        "description": "Toyota Corolla с пробегом из Китая. Заводской окрас кузова, проверенная надёжность."
    },
    {
        "id": "vw-golf-2023",
        "brand": "Volkswagen",
        "model": "Golf",
        "year": 2023,
        "engineVolume": 1.4,
        "horsePower": 149,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 36000,
        "price": 2390000,
        "features": [
            "Культовый хэтчбек · Турбо 149 л.с.",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Подогрев сидений · Парктроники",
            "Пробег 36 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/VW-Golf/VW-Golf-1.jpg",
            "images/cars/VW-Golf/VW-Golf-2.jpg",
            "images/cars/VW-Golf/VW-Golf-3.jpg",
            "images/cars/VW-Golf/VW-Golf-4.jpg",
            "images/cars/VW-Golf/VW-Golf-5.jpg",
            "images/cars/VW-Golf/VW-Golf-6.jpg",
            "images/cars/VW-Golf/VW-Golf-7.jpg"
        ],
        "description": "VW Golf из Китая с пробегом 36 000 км. Отличное состояние и легендарная управляемость."
    },
    {
        "id": "honda-vezel-2023",
        "brand": "Honda",
        "model": "Vezel",
        "year": 2023,
        "engineVolume": 1.5,
        "horsePower": 124,
        "transmission": "Вариатор",
        "drivetrain": "Передний привод",
        "mileage": 20000,
        "price": 2090000,
        "features": [
            "Компактный кроссовер · Гибрид",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Подогрев сидений · Бесключевой доступ",
            "Пробег 20 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Honda-Vezel/Honda-Vezel-1.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-2.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-3.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-4.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-5.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-6.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-7.jpg",
            "images/cars/Honda-Vezel/Honda-Vezel-8.jpg"
        ],
        "description": "Honda Vezel из Китая с пробегом. Заводской окрас кузова, отличное состояние."
    },
    {
        "id": "skoda-octavia-2023",
        "brand": "Skoda",
        "model": "Octavia",
        "year": 2023,
        "engineVolume": 1.4,
        "horsePower": 149,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 13000,
        "price": 2450000,
        "features": [
            "Premium Edition · Почти новая",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Подогрев сидений",
            "Пробег 13 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Skoda-Octavia/Skoda-Octavia-1.jpg",
            "images/cars/Skoda-Octavia/Skoda-Octavia-2.jpg",
            "images/cars/Skoda-Octavia/Skoda-Octavia-3.jpg",
            "images/cars/Skoda-Octavia/Skoda-Octavia-4.jpg",
            "images/cars/Skoda-Octavia/Skoda-Octavia-5.jpg",
            "images/cars/Skoda-Octavia/Skoda-Octavia-6.jpg",
            "images/cars/Skoda-Octavia/Skoda-Octavia-7.jpg",
            "images/cars/Skoda-Octavia/Skoda-Octavia-8.jpg"
        ],
        "description": "Skoda Octavia Premium Edition из Китая. Пробег всего 13 000 км. Заводской окрас."
    },
    {
        "id": "mazda-cx30-2023",
        "brand": "Mazda",
        "model": "CX-30",
        "year": 2023,
        "engineVolume": 2,
        "horsePower": 158,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 20000,
        "price": 2510000,
        "features": [
            "KODO Design · Японская эстетика",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Подогрев сидений",
            "Пробег 20 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Mazda-CX-30/Mazda-CX-30-1.jpg",
            "images/cars/Mazda-CX-30/Mazda-CX-30-2.jpg",
            "images/cars/Mazda-CX-30/Mazda-CX-30-3.jpg",
            "images/cars/Mazda-CX-30/Mazda-CX-30-4.jpg",
            "images/cars/Mazda-CX-30/Mazda-CX-30-5.jpg",
            "images/cars/Mazda-CX-30/Mazda-CX-30-6.jpg"
        ],
        "description": "Mazda CX-30 из Китая. Итоговая стоимость с учетом всех расходов:."
    },
    {
        "id": "jetta-vs7-2022",
        "brand": "Jetta",
        "model": "VS7",
        "year": 2022,
        "engineVolume": 1.4,
        "horsePower": 150,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 40000,
        "price": 2090000,
        "priceIsFrom": true,
        "features": [
            "7 мест · Просторный семейный кроссовер",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Парктроники",
            "Пробег 40 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Jetta-VS7/Jetta-VS7-1.jpg",
            "images/cars/Jetta-VS7/Jetta-VS7-2.jpg",
            "images/cars/Jetta-VS7/Jetta-VS7-3.jpg",
            "images/cars/Jetta-VS7/Jetta-VS7-4.jpg",
            "images/cars/Jetta-VS7/Jetta-VS7-5.jpg",
            "images/cars/Jetta-VS7/Jetta-VS7-6.jpg"
        ],
        "description": "Jetta VS7 из Китая с пробегом. Итоговая стоимость с учетом всех расходов:."
    },
    {
        "id": "vw-t-roc-2023",
        "brand": "Volkswagen",
        "model": "T-Roc",
        "year": 2023,
        "engineVolume": 1.4,
        "horsePower": 149,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 27900,
        "price": 2320000,
        "features": [
            "Европейский характер · Турбо 149 л.с.",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Подогрев сидений",
            "Пробег 27 900 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Volkswagen-T-Roc/Volkswagen-T-Roc-1.jpg",
            "images/cars/Volkswagen-T-Roc/Volkswagen-T-Roc-2.jpg",
            "images/cars/Volkswagen-T-Roc/Volkswagen-T-Roc-3.jpg",
            "images/cars/Volkswagen-T-Roc/Volkswagen-T-Roc-4.jpg",
            "images/cars/Volkswagen-T-Roc/Volkswagen-T-Roc-5.jpg",
            "images/cars/Volkswagen-T-Roc/Volkswagen-T-Roc-6.jpg",
            "images/cars/Volkswagen-T-Roc/Volkswagen-T-Roc-7.jpg"
        ],
        "description": "Volkswagen T-Roc 2023 из Китая. Пробег 27 900 км. Заводской окрас кузова."
    },
    {
        "id": "audi-q5-2026",
        "brand": "Audi",
        "model": "Q5",
        "year": 2026,
        "engineVolume": 2,
        "horsePower": 204,
        "transmission": "Робот",
        "drivetrain": "Полный привод",
        "mileage": 0,
        "price": 5690000,
        "features": [
            "Флагман немецкого люкса · Новая",
            "Полный привод quattro · 204 л.с.",
            "Кожаный салон · Панорамная крыша",
            "Matrix LED фары · Камера 360°",
            "Адаптивный круиз-контроль · Bang & Olufsen",
            "Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Audi-Q5/Audi-Q5-1.jpg",
            "images/cars/Audi-Q5/Audi-Q5-2.jpg",
            "images/cars/Audi-Q5/Audi-Q5-3.jpg",
            "images/cars/Audi-Q5/Audi-Q5-4.jpg",
            "images/cars/Audi-Q5/Audi-Q5-5.jpg"
        ],
        "description": "Audi Q5 2026 новая из Китая. Полный привод, мощный турбомотор 204 л.с."
    },
    {
        "id": "volkswagen-jetta-2026",
        "brand": "Volkswagen",
        "model": "Jetta",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 158,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 2290000,
        "features": [
            "Максимальная комплектация · Новый",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Подогрев сидений",
            "Бесключевой доступ · Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Volkswagen-Jetta/Volkswagen-Jetta-1.jpg",
            "images/cars/Volkswagen-Jetta/Volkswagen-Jetta-2.jpg",
            "images/cars/Volkswagen-Jetta/Volkswagen-Jetta-3.jpg",
            "images/cars/Volkswagen-Jetta/Volkswagen-Jetta-4.jpg",
            "images/cars/Volkswagen-Jetta/Volkswagen-Jetta-5.jpg",
            "images/cars/Volkswagen-Jetta/Volkswagen-Jetta-6.jpg"
        ],
        "description": "Volkswagen Jetta 2026 новый из Китая. Максимальная комплектация."
    },
    {
        "id": "audi-q3-2026",
        "brand": "Audi",
        "model": "Q3",
        "year": 2026,
        "engineVolume": 1.5,
        "horsePower": 160,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 0,
        "price": 3490000,
        "features": [
            "Немецкий компактный SUV · Новая",
            "Кожаный руль · Климат-контроль",
            "LED фары · Камера заднего вида",
            "Круиз-контроль · Парктроники",
            "Бесключевой доступ · Цена под ключ"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Audi-Q3/Audi-Q3-1.jpg",
            "images/cars/Audi-Q3/Audi-Q3-2.jpg",
            "images/cars/Audi-Q3/Audi-Q3-3.jpg",
            "images/cars/Audi-Q3/Audi-Q3-4.jpg",
            "images/cars/Audi-Q3/Audi-Q3-5.jpg",
            "images/cars/Audi-Q3/Audi-Q3-6.jpg",
            "images/cars/Audi-Q3/Audi-Q3-7.jpg",
            "images/cars/Audi-Q3/Audi-Q3-8.jpg",
            "images/cars/Audi-Q3/Audi-Q3-9.jpg",
            "images/cars/Audi-Q3/Audi-Q3-10.jpg",
            "images/cars/Audi-Q3/Audi-Q3-11.jpg",
            "images/cars/Audi-Q3/Audi-Q3-12.jpg",
            "images/cars/Audi-Q3/Audi-Q3-13.jpg",
            "images/cars/Audi-Q3/Audi-Q3-14.jpg",
            "images/cars/Audi-Q3/Audi-Q3-15.jpg"
        ],
        "description": "Audi Q3 2026 новая из Китая. Итоговая стоимость с учетом всех расходов:."
    },
    {
        "id": "audi-a3-2023",
        "brand": "Audi",
        "model": "A3",
        "year": 2023,
        "engineVolume": 1.4,
        "horsePower": 150,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 35000,
        "price": 2190000,
        "priceIsFrom": true,
        "features": [
            "Турбо 150 л.с. · Немецкий стиль",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Парктроники",
            "Пробег 35 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Audi-A3/Audi-A3-1.jpg",
            "images/cars/Audi-A3/Audi-A3-2.jpg",
            "images/cars/Audi-A3/Audi-A3-3.jpg",
            "images/cars/Audi-A3/Audi-A3-4.jpg",
            "images/cars/Audi-A3/Audi-A3-5.jpg",
            "images/cars/Audi-A3/Audi-A3-6.jpg",
            "images/cars/Audi-A3/Audi-A3-7.jpg",
            "images/cars/Audi-A3/Audi-A3-8.jpg",
            "images/cars/Audi-A3/Audi-A3-9.jpg",
            "images/cars/Audi-A3/Audi-A3-10.jpg",
            "images/cars/Audi-A3/Audi-A3-11.jpg"
        ],
        "description": "Audi A3 2023 из Китая с пробегом. Заводской окрас кузова."
    },
    {
        "id": "audi-q2-2022",
        "brand": "Audi",
        "model": "Q2",
        "year": 2022,
        "engineVolume": 1.4,
        "horsePower": 150,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 45000,
        "price": 2290000,
        "priceIsFrom": true,
        "features": [
            "Компактный немецкий SUV",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Парктроники",
            "Пробег 45 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Audi-Q2/Audi-Q2-1.jpg",
            "images/cars/Audi-Q2/Audi-Q2-2.jpg",
            "images/cars/Audi-Q2/Audi-Q2-3.jpg",
            "images/cars/Audi-Q2/Audi-Q2-4.jpg",
            "images/cars/Audi-Q2/Audi-Q2-5.jpg",
            "images/cars/Audi-Q2/Audi-Q2-6.jpg",
            "images/cars/Audi-Q2/Audi-Q2-7.jpg",
            "images/cars/Audi-Q2/Audi-Q2-8.jpg",
            "images/cars/Audi-Q2/Audi-Q2-9.jpg",
            "images/cars/Audi-Q2/Audi-Q2-10.jpg"
        ],
        "description": "Audi Q2 2022 из Китая с пробегом. Немецкое качество и городской характер."
    },
    {
        "id": "volkswagen-passat-2023",
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2023,
        "engineVolume": 1.4,
        "horsePower": 150,
        "transmission": "Автомат",
        "drivetrain": "Передний привод",
        "mileage": 30000,
        "price": 2390000,
        "priceIsFrom": true,
        "features": [
            "Бизнес-класс · Просторный лифтбек",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Подогрев сидений",
            "Пробег 30 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-1.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-2.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-3.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-4.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-5.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-6.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-7.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-8.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-9.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-10.jpg",
            "images/cars/Volkswagen-Passat/Volkswagen-Passat-11.jpg"
        ],
        "description": "Volkswagen Passat 2023 из Китая. Бизнес-класс с немецким характером."
    },
    {
        "id": "bmw-120i-2023",
        "brand": "BMW",
        "model": "120i",
        "year": 2023,
        "engineVolume": 1.5,
        "horsePower": 136,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 30000,
        "price": 1950000,
        "priceIsFrom": true,
        "features": [
            "Баварский стиль · Турбо 136 л.с.",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Подогрев сидений",
            "Пробег 30 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/BMW-120i/BMW-120i-1.jpg",
            "images/cars/BMW-120i/BMW-120i-2.jpg",
            "images/cars/BMW-120i/BMW-120i-3.jpg",
            "images/cars/BMW-120i/BMW-120i-4.jpg",
            "images/cars/BMW-120i/BMW-120i-5.jpg",
            "images/cars/BMW-120i/BMW-120i-6.jpg",
            "images/cars/BMW-120i/BMW-120i-8.jpg",
            "images/cars/BMW-120i/BMW-120i-9.jpg",
            "images/cars/BMW-120i/BMW-120i-10.jpg",
            "images/cars/BMW-120i/BMW-120i-11.jpg"
        ],
        "description": "BMW 120i 2023 из Китая с пробегом. Спортивный характер и баварский стиль."
    },
    {
        "id": "mercedes-gla-2022",
        "brand": "Mercedes-Benz",
        "model": "GLA",
        "year": 2022,
        "engineVolume": 1.3,
        "horsePower": 136,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 40000,
        "price": 2990000,
        "priceIsFrom": true,
        "features": [
            "Немецкий премиум SUV",
            "Кожаный руль · Климат-контроль",
            "LED фары · Камера заднего вида",
            "Круиз-контроль · Парктроники",
            "Пробег 40 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Mercedes-GLA/Mercedes-GLA-1.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-2.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-3.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-4.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-5.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-6.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-7.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-8.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-9.jpg",
            "images/cars/Mercedes-GLA/Mercedes-GLA-10.jpg"
        ],
        "description": "Mercedes-Benz GLA 2022 из Китая с пробегом. Заводской окрас кузова."
    },
    {
        "id": "mercedes-a180l-2022",
        "brand": "Mercedes-Benz",
        "model": "A-Class 180L",
        "year": 2022,
        "engineVolume": 1.3,
        "horsePower": 136,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 35000,
        "price": 2290000,
        "features": [
            "Немецкий премиум · Длиннобазная A-Class",
            "Кожаный руль · Климат-контроль",
            "LED фары · Камера заднего вида",
            "Круиз-контроль · Парктроники",
            "Пробег 35 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-1.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-2.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-3.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-4.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-5.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-6.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-7.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-8.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-9.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-10.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-11.jpg",
            "images/cars/Mercedes-A-Class-180L/Mercedes-A-Class-180L-12.jpg"
        ],
        "description": "Mercedes-Benz A-Class 180L 2022 из Китая с пробегом."
    },
    {
        "id": "mercedes-glb-2022",
        "brand": "Mercedes-Benz",
        "model": "GLB",
        "year": 2022,
        "engineVolume": 1.3,
        "horsePower": 136,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 40000,
        "price": 2990000,
        "features": [
            "Компактный немецкий SUV",
            "Кожаный салон · Климат-контроль",
            "LED фары · Камера заднего вида",
            "Круиз-контроль · Парктроники",
            "Пробег 40 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Mercedes-GLB/Mercedes-GLB-1.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-2.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-3.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-4.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-5.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-6.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-7.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-8.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-9.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-10.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-11.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-12.jpg",
            "images/cars/Mercedes-GLB/Mercedes-GLB-13.jpg"
        ],
        "description": "Mercedes-Benz GLB 2022 из Китая. Просторный салон с кожаной отделкой."
    },
    {
        "id": "bmw-x2-2022",
        "brand": "BMW",
        "model": "X2",
        "year": 2022,
        "engineVolume": 1.5,
        "horsePower": 136,
        "transmission": "Робот",
        "drivetrain": "Передний привод",
        "mileage": 35000,
        "price": 1990000,
        "features": [
            "M Sport Edition · Уникальный тёмно-зелёный окрас",
            "Кожаный руль · Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Золотые решётки гриля · Спортивная подвеска",
            "Пробег 35 000 км"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/BMW-X2/BMW-X2-1.jpg",
            "images/cars/BMW-X2/BMW-X2-2.jpg",
            "images/cars/BMW-X2/BMW-X2-3.jpg",
            "images/cars/BMW-X2/BMW-X2-4.jpg",
            "images/cars/BMW-X2/BMW-X2-5.jpg",
            "images/cars/BMW-X2/BMW-X2-6.jpg",
            "images/cars/BMW-X2/BMW-X2-7.jpg",
            "images/cars/BMW-X2/BMW-X2-8.jpg",
            "images/cars/BMW-X2/BMW-X2-9.jpg",
            "images/cars/BMW-X2/BMW-X2-10.jpg",
            "images/cars/BMW-X2/BMW-X2-11.jpg"
        ],
        "description": "BMW X2 2022 M Sport Edition из Китая. Уникальный тёмно-зелёный окрас с золотыми акцентами."
    },
    {
        "id": "subaru-forester-2022",
        "brand": "Subaru",
        "model": "Forester",
        "year": 2022,
        "engineVolume": 2,
        "horsePower": 154,
        "transmission": "Вариатор",
        "drivetrain": "Полный привод",
        "mileage": 40000,
        "price": 2990000,
        "features": [
            "Полный привод Symmetrical AWD · Boxer 2.0",
            "Панорамная крыша · Кожаный руль",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Пробег 40 000 км · Японское качество"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "alexcash2025",
        "images": [
            "images/cars/Subaru-Forester/Subaru-Forester-1.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-2.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-3.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-4.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-5.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-6.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-7.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-8.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-9.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-10.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-11.jpg",
            "images/cars/Subaru-Forester/Subaru-Forester-12.jpg"
        ],
        "description": "Subaru Forester 2022 из Китая. Легендарный симметричный полный привод."
    },
    {
        "id": "honda-civic-2022",
        "brand": "Honda",
        "model": "Civic",
        "year": 2022,
        "engineVolume": 1.5,
        "horsePower": 129,
        "transmission": "Вариатор",
        "drivetrain": "Передний привод",
        "mileage": 35000,
        "price": 1990000,
        "features": [
            "Спортивный облик · Японская надёжность",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Подогрев сидений",
            "Пробег 35 000 км · Заводской окрас"
        ],
        "location": "Китай",
        "status": "Под заказ",
        "manager": "Michail2004",
        "images": [
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-1.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-2.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-3.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-4.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-5.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-6.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-7.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-8.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-9.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-10.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-11.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-12.jpg",
            "images/cars/Honda-Civic-2022/Honda-Civic-2022-13.jpg"
        ],
        "description": "Honda Civic 2022 из Китая. Спортивный дизайн и японская надёжность."
    },
    {
        "id": "mazda-3-axela-2026",
        "brand": "Mazda",
        "model": "3 Axela",
        "year": 2026,
        "price": 2490000,
        "priceIsFrom": false,
        "mileage": 0,
        "engineVolume": 2.0,
        "horsePower": 158,
        "transmission": "Автомат",
        "drivetrain": "2WD",
        "location": "Китай",
        "status": "Новый",
        "features": [
            "Новая · Японская эстетика KODO",
            "Premium LED фары · Климат-контроль",
            "Камера заднего вида · Круиз-контроль",
            "Кожаный руль · Подогрев сидений",
            "Бесключевой доступ · Цена под ключ"
        ],
        "description": "Совершенно новая Mazda 3 Axela — это воплощение японской эстетики и драйва. Яркий дизайн, роскошный технологичный салон и превосходная управляемость. Автомобиль, который притягивает взгляды!",
        "manager": "alexcash2025",
        "images": [
            "images/cars/mazda-3-axela-2026/mazda-3-axela-2026-1.jpg",
            "images/cars/mazda-3-axela-2026/mazda-3-axela-2026-2.jpg",
            "images/cars/mazda-3-axela-2026/mazda-3-axela-2026-3.jpg",
            "images/cars/mazda-3-axela-2026/mazda-3-axela-2026-4.jpg",
            "images/cars/mazda-3-axela-2026/mazda-3-axela-2026-5.jpg",
            "images/cars/mazda-3-axela-2026/mazda-3-axela-2026-6.jpg",
            "images/cars/mazda-3-axela-2026/mazda-3-axela-2026-7.jpg",
            "images/cars/mazda-3-axela-2026/mazda-3-axela-2026-8.jpg"
        ]
    },
    {
        "id": "kia-k5",
        "brand": "Kia",
        "model": "K5",
        "year": 2022,
        "price": 3190000,
        "priceIsFrom": false,
        "mileage": 32000,
        "engineVolume": 2.0,
        "horsePower": 160,
        "transmission": "Автомат",
        "drivetrain": "2WD",
        "location": "Корея",
        "status": "С пробегом",
        "features": [
            "Цена под ключ · Корея",
            "Кожаный салон · Климат-контроль",
            "LED фары · Камера заднего вида",
            "Адаптивный круиз-контроль · Парктроники",
            "Бесключевой доступ · Подогрев сидений",
            "Пробег 32 000 км"
        ],
        "description": "Эффектный седан Kia K5 напрямую из Кореи. Итоговая стоимость с учетом всех расходов: указана. Проверенный автомобиль с честным пробегом.",
        "manager": "Michail2004",
        "images": [
            "images/cars/kia-k5-2022/kia-k5-2022-1.jpg",
            "images/cars/kia-k5-2022/kia-k5-2022-2.jpg",
            "images/cars/kia-k5-2022/kia-k5-2022-3.jpg",
            "images/cars/kia-k5-2022/kia-k5-2022-4.jpg",
            "images/cars/kia-k5-2022/kia-k5-2022-5.jpg",
            "images/cars/kia-k5-2022/kia-k5-2022-6.jpg"
        ]
    },
    {
        "id": "hyundai-avante-2023",
        "brand": "Hyundai",
        "model": "Avante",
        "year": 2023,
        "price": 1890000,
        "priceIsFrom": false,
        "mileage": 43000,
        "engineVolume": 1.6,
        "horsePower": 123,
        "transmission": "Автомат",
        "drivetrain": "2WD",
        "location": "Корея",
        "status": "С пробегом",
        "features": [
            "Городской седан · Корея",
            "Климат-контроль · LED фары",
            "Камера заднего вида · Круиз-контроль",
            "Подогрев сидений · ЖК-экран",
            "Пробег 43 000 км · Малый расход топлива"
        ],
        "description": "Надежный и экономичный Hyundai Avante 2023 года. Отличный выбор для города с небольшим расходом топлива и комфортным салоном.",
        "manager": "alexcash2025",
        "images": [
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-1.jpg",
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-2.jpg",
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-3.jpg",
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-4.jpg",
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-5.jpg",
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-6.jpg",
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-7.jpg",
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-8.jpg",
            "images/cars/hyundai-avante-2023/hyundai-avante-2023-9.jpg"
        ]
    },
    {
        "id": "hyundai-tucson-2025",
        "brand": "Hyundai",
        "model": "Tucson",
        "year": 2025,
        "price": 3290000,
        "priceIsFrom": false,
        "mileage": 27000,
        "engineVolume": 1.6,
        "horsePower": 180,
        "transmission": "Робот",
        "drivetrain": "2WD",
        "location": "Корея",
        "status": "С пробегом",
        "features": [
            "Современный кузов 2025 г. · Корея",
            "Турбо 1.6 · 180 л.с. · Робот",
            "Кожаный салон · Климат-контроль",
            "LED фары · Камера 360°",
            "Адаптивный круиз-контроль · Парктроники",
            "Пробег 27 000 км"
        ],
        "description": "Свежий кроссовер Hyundai Tucson в современном кузове 2025 модельного года. Динамичный 1.6-турбо мотор, выразительная внешность и богатая комплектация.",
        "manager": "Michail2004",
        "images": [
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-1.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-2.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-3.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-4.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-5.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-6.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-7.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-8.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-9.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-10.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-11.jpg",
            "images/cars/hyundai-tucson-2025/hyundai-tucson-2025-12.jpg"
        ]
    }
];
